[package]
name = "open-libra-scene-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
wasm-bindgen = "0.2"
uuid = { version = "1.24", features = ["js", "serde", "v5", "v7"] }
console_error_panic_hook = "0.1"
i_overlay = "8.1.0"
