export type Mode = "design" | "developer" | "review";
export type EntityId = string;
export type PageSummary = { id: EntityId; name: string; description: string };
export type ColorAsset = { id: EntityId; name: string; value: string };
export type ShadowSummary = {
  kind: "outer" | "inner";
  color: number[];
  offset_x: number;
  offset_y: number;
  blur: number;
  spread: number;
  enabled: boolean;
};
export type NodeSummary = {
  id: EntityId;
  name: string;
  kind: "frame" | "rectangle" | "group" | "text";
  parent_id?: EntityId;
  x: number;
  y: number;
  width: number;
  height: number;
  fill: number[];
  stroke: number[];
  stroke_width: number;
  corner_radius: number;
  opacity: number;
  rotation: number;
  flip_x: boolean;
  flip_y: boolean;
  shadows: ShadowSummary[];
  layout_mode: "none" | "row" | "column";
  layout_align: "start" | "center" | "end";
  layout_justify: "start" | "center" | "end";
  layout_gap: number;
  layout_padding: number[];
  width_sizing: "fixed" | "fill";
  auto_height: boolean;
  guide_mode: "none" | "grid" | "columns";
  guide_count: number;
  guide_gap: number;
  guide_color: number[];
  guide_opacity: number;
  locked: boolean;
};
export type DocumentReadModel = {
  schema_version: number;
  active_page_id: EntityId;
  pages: PageSummary[];
  nodes: NodeSummary[];
  document_colors: ColorAsset[];
};
